/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DAO_Book;
import dao.DAO_Table;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jdbcHelper.DateHelper;
import model.Book;
import model.Table;

/**
 *
 * @author Admin
 */
public final class PalBook extends javax.swing.JPanel {

    /**
     * Creates new form PalBook
     */
    DAO_Book daoBook = new DAO_Book();
    DAO_Table daoTable = new DAO_Table();
    int index;

    public PalBook() {
        initComponents();

        loadTable();
        loadDsDatBan();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbbTenBan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNgayDat = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        radNo = new javax.swing.JRadioButton();
        radDaTT = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDsDatBan = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblStt = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ĐẶT BÀN");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Tên khách hàng");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Bàn số");

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Số điện thoại");

        cbbTenBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbTenBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Trả trước");

        txtNgayDat.setBackground(new java.awt.Color(102, 255, 204));
        txtNgayDat.setDateFormatString("MM/dd/yyyy");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ngày đặt");

        radNo.setBackground(new java.awt.Color(102, 255, 204));
        buttonGroup1.add(radNo);
        radNo.setText("Không");

        radDaTT.setBackground(new java.awt.Color(102, 255, 204));
        buttonGroup1.add(radDaTT);
        radDaTT.setText("Đã thanh toán");

        tbDsDatBan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbDsDatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách hàng", "Họ Tên", "Số điện thoại", "Bàn số", "Ngày đặt", "Trả trước"
            }
        ));
        tbDsDatBan.setGridColor(new java.awt.Color(255, 255, 255));
        tbDsDatBan.setRowHeight(35);
        tbDsDatBan.setRowMargin(5);
        tbDsDatBan.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tbDsDatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDsDatBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDsDatBan);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_48px.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_file_filled_48px.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_48px.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_restart_48px.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblStt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(radNo)
                                .addGap(18, 18, 18)
                                .addComponent(radDaTT)
                                .addGap(156, 156, 156)
                                .addComponent(lblStt, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel1)
                                        .addComponent(txtTenKH)
                                        .addComponent(jLabel2)
                                        .addComponent(txtSdt, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(cbbTenBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnClear))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNo)
                    .addComponent(radDaTT)
                    .addComponent(lblStt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        insert();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbDsDatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDsDatBanMouseClicked
        int row = tbDsDatBan.getSelectedRow();
        if (row >= 0) {
            index = row;
            showDelt();
            lblStt.setText("");
        }
    }//GEN-LAST:event_tbDsDatBanMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    public void insert() {
        if (radDaTT.isSelected()) {
            Book model = getModel();
            try {
                daoBook.insert(model);
                loadDsDatBan();

                // sau khi đặt bàn xong ta update lại trạng thái bàn ở bảng Table
                Table tabModel = new Table();
                Table cbbModel = (Table) cbbTenBan.getSelectedItem();
                tabModel.setMaBan(cbbModel.getMaBan());
                tabModel.setTenBan(cbbTenBan.getSelectedItem().toString());
                tabModel.setTrangThai("Đã đặt");
                daoTable.update(tabModel);

                lblStt.setText("ĐẶT BÀN THÀNH CÔNG");
                
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Phải thanh toán trước mới được đặt bàn");
        }

    }

    public void update() {

        Book model = getModel();
        try {
            daoBook.update(model);
            loadDsDatBan();
            lblStt.setText("CẬP NHẬP THÀNH CÔNG");
        } catch (Exception e) {
        }
    }

    public void delete() {
        int maKh = (int) tbDsDatBan.getValueAt(index, 0);
        
        
        Table tabModel = new Table();
        Table cbbModel = (Table) cbbTenBan.getSelectedItem();
        tabModel.setMaBan(cbbModel.getMaBan());
        tabModel.setTenBan(cbbTenBan.getSelectedItem().toString());
        tabModel.setTrangThai("Trống");
        daoTable.update(tabModel);
        
        daoBook.delete(maKh);
        loadDsDatBan();

           

        lblStt.setText("XÓA THÀNH CÔNG");
    }

    public void clear() {
        Book model = new Book();
        setModel(model);
    }

    public void showDelt() {
        int maKh = (int) tbDsDatBan.getValueAt(index, 0);
        Book model = daoBook.findById(maKh);
        setModel(model);
    }

    public void loadTable() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbTenBan.getModel();
        model.removeAllElements();

        ArrayList<Table> listTable = daoTable.select();
        for (Table table : listTable) {
            model.addElement(table);
        }
    }

    public void loadDsDatBan() {
        DefaultTableModel model = (DefaultTableModel) tbDsDatBan.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Book> list = daoBook.select();
            for (Book bk : list) {
                Object[] row = new Object[]{
                    bk.getMaKH(),
                    bk.getTenKH(),
                    bk.getSdt(),
                    daoTable.findById(bk.getMaBan()).getTenBan(),
                    bk.getNgayDat(),
                    bk.getSttTT()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }

    }

    public void setModel(Book model) {
        Table table = (Table) cbbTenBan.getSelectedItem();
        txtTenKH.setToolTipText(Integer.toString(model.getMaKH()));
        txtTenKH.setText(model.getTenKH());
        txtSdt.setText(model.getSdt());
        cbbTenBan.getModel().setSelectedItem(daoTable.findById(model.getMaBan()));
        ((JTextField) txtNgayDat.getDateEditor().getUiComponent()).setText(DateHelper.toString(new Date()));
        radNo.setSelected((radNo.isSelected()));
        radNo.setSelected((!(radNo.isSelected())));
    }

    public Book getModel() {
        Book model = new Book();
        Table cbbModel = (Table) cbbTenBan.getSelectedItem();
        model.setMaKH(Integer.parseInt(txtTenKH.getToolTipText()));
        model.setTenKH(txtTenKH.getText());
        model.setSdt(txtSdt.getText());
        model.setMaBan(cbbModel.getMaBan());
        if (radNo.isSelected()) {
            model.setSttTT("Chưa thanh toán");
        } else {
            model.setSttTT("Đã thanh toán");
        }
        String date = ((JTextField) txtNgayDat.getDateEditor().getUiComponent()).getText();
        model.setNgayDat(date);
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTenBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStt;
    private javax.swing.JRadioButton radDaTT;
    private javax.swing.JRadioButton radNo;
    private javax.swing.JTable tbDsDatBan;
    private com.toedter.calendar.JDateChooser txtNgayDat;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
