/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DAO_Category;
import dao.DAO_Menu;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.function.ObjDoubleConsumer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Menu;

/**
 *
 * @author Admin
 */
public class PalMemu extends javax.swing.JPanel {

    /**
     * Creates new form PalMemu
     */
    DAO_Category daoCate = new DAO_Category();
    DAO_Menu daoMenu = new DAO_Menu();
    int index;
    int maLoai;

    public PalMemu() {
        initComponents();
        loadTypeMenu();       
        loadComboBoxType();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        palLoai = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDsMenu = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        palEditMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbDVT = new javax.swing.JComboBox<>();
        txtDonGia = new javax.swing.JTextField();
        cbbType = new javax.swing.JComboBox<>();
        txtTenMon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 255, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MENU");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        palLoai.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout palLoaiLayout = new javax.swing.GroupLayout(palLoai);
        palLoai.setLayout(palLoaiLayout);
        palLoaiLayout.setHorizontalGroup(
            palLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        palLoaiLayout.setVerticalGroup(
            palLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(palLoai);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbDsMenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tbDsMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MÃ MÓN", "TÊN MÓN", "ĐƠN GIÁ"
            }
        ));
        tbDsMenu.setGridColor(new java.awt.Color(255, 255, 255));
        tbDsMenu.setRowHeight(35);
        tbDsMenu.setRowMargin(5);
        tbDsMenu.setSelectionBackground(new java.awt.Color(255, 51, 51));
        tbDsMenu.setShowHorizontalLines(false);
        tbDsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDsMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDsMenu);
        if (tbDsMenu.getColumnModel().getColumnCount() > 0) {
            tbDsMenu.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbDsMenu.getColumnModel().getColumn(1).setResizable(false);
            tbDsMenu.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 51, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_filled_48px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        palEditMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Đơn vị tính");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Loại");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Đơn giá");

        cbbDVT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Lon", "Đĩa", "Xuất", "Con", "Lồi", "Cốc", "Ly", "Chai" }));

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cbbType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTenMon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Tên món");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_48px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_update_file_filled_48px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_48px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_restart_48px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("CHECK lại DVT, LOẠI, GIÁ");

        javax.swing.GroupLayout palEditMenuLayout = new javax.swing.GroupLayout(palEditMenu);
        palEditMenu.setLayout(palEditMenuLayout);
        palEditMenuLayout.setHorizontalGroup(
            palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palEditMenuLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(palEditMenuLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4))
                    .addGroup(palEditMenuLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)))
                .addGap(56, 56, 56))
            .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(palEditMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(palEditMenuLayout.createSequentialGroup()
                            .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(palEditMenuLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenMon)
                                .addComponent(cbbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                .addComponent(cbbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        palEditMenuLayout.setVerticalGroup(
            palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, palEditMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(palEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(palEditMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGap(2, 2, 2)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(palEditMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(palEditMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbDsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDsMenuMouseClicked
        int row = tbDsMenu.getSelectedRow();
        if (row >= 0) {
            index = row;
            showDetal();
        }
    }//GEN-LAST:event_tbDsMenuMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadDSMenu();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         insert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public void loadTypeMenu() {
        // Lấy số loại
        ArrayList<Category> list = daoCate.select();
        //Chia layout
        palLoai.setLayout(new GridLayout(list.size(), 1, 5, 5));
        palLoai.removeAll();
        palLoai.updateUI();
        
        JLabel lbl[] = new JLabel[list.size()];
        
        for (int i = 0; i < list.size(); i++) {
            lbl[i] = new JLabel(list.get(i).getTenLoai());
            lbl[i].setCursor(new Cursor(Cursor.HAND_CURSOR));
            lbl[i].setPreferredSize(new Dimension(200, 50));
            lbl[i].setHorizontalAlignment(JLabel.CENTER);
            lbl[i].setFont(new Font("Tahoma", Font.PLAIN, 18));
            lbl[i].setToolTipText(Integer.toString(list.get(i).getMaLoai()));
            
            lbl[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    System.out.println("Thực hiện khi click vào loại");
                    maLoai = Integer.parseInt(((JLabel) e.getSource()).getToolTipText());
                    System.out.println(maLoai);
                    loadDSMenu();
                }
            });
            palLoai.add(lbl[i]);
        }
        
    }
    
    public void loadDSMenu() {
        DefaultTableModel model = (DefaultTableModel) tbDsMenu.getModel();
        model.setRowCount(0);
        try {
            String search = txtSearch.getText();
            ArrayList<Menu> list = new ArrayList<>();
            if (search.equals("")) {
                list = daoMenu.findByMaLoai(maLoai);
            } else {
                list = daoMenu.findByTenMon(maLoai, search);
            }
                    
            for (Menu menu : list) {
                Object[] row = new Object[]{
                    menu.getMaMon(),
                    menu.getTenMon(),
                    menu.getDonGia()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }
    
    
    public void loadComboBoxType() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbType.getModel();
        model.removeAllElements();
        ArrayList<Category> listType = daoCate.select();
        for (Category category : listType) {
            model.addElement(category);
        }
    }
    
    public void insert(){
       Menu model = getModel();
        try {
            daoMenu.insert(model);
            JOptionPane.showMessageDialog(this, "Thêm thánh công");
            loadDSMenu();
            
        } catch (Exception e) {
            e.printStackTrace();
        }       
    }
    
    public void update(){
        Menu model = getModel();
        try {
            daoMenu.update(model);
            JOptionPane.showMessageDialog(this, "Update thánh công");
            loadDSMenu();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void delete(){
        int maMon = Integer.parseInt(txtTenMon.getToolTipText());
        try {
            daoMenu.delete(maMon);
            JOptionPane.showMessageDialog(this, "Delete thánh công");
            loadDSMenu();
            clear();
        } catch (Exception e) {
        }
    }
    
    public void showDetal() {
        int maMon = (int) tbDsMenu.getValueAt(index, 0);
        Menu menu = daoMenu.findById(maMon);
        setModel(menu);
    }

    public void clear(){
        Menu menu = new Menu();
        setModel(menu);
    }
    
    public void setModel(Menu model){
        Category cate = (Category) cbbType.getSelectedItem();
        txtTenMon.setToolTipText(Integer.toString(model.getMaMon()));
        txtTenMon.setText(model.getTenMon());
        cbbType.getModel().setSelectedItem(daoCate.findById(model.getMaLoai()));
        txtDonGia.setText(model.getDonGia()+"");
        cbbDVT.getModel().setSelectedItem(model.getDVT());
    }
    
    public Menu getModel(){
        Menu model = new Menu();
        Category cate = (Category) cbbType.getSelectedItem();
        model.setMaMon(Integer.parseInt(txtTenMon.getToolTipText()));
        model.setTenMon(txtTenMon.getText());
        model.setMaLoai(cate.getMaLoai());
        model.setDonGia(Double.parseDouble(txtDonGia.getText()));
        model.setDVT(cbbDVT.getSelectedItem().toString());
        return model;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbDVT;
    private javax.swing.JComboBox<String> cbbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JPanel palEditMenu;
    private javax.swing.JPanel palLoai;
    private javax.swing.JTable tbDsMenu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
